import Navbar from "../components/Navbar/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
        />
      </head>
      <body>
        <header>
          <Navbar />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
